version: '3'
services:
  api:
    build:
      context: ./src
      dockerfile: Dockerfile
    environment:
      MYSQL_PASSWORD: datascientest1234
      MYSQL_URL: mysql:3306
    ports:
      - 8000:8000

  mysql:
    container_name: mysql
    image: datascientest/mysql-k8s:1.0.0
    ports:
      - "3306:3306"  # Maps port 5432 on the host to port 5432 in the container

  
    
