apiVersion: v1
kind: Service
metadata:
  name: monservicenodeport
spec:
  type: NodePort
  selector:
    app: nginx-deployment
  ports:
  - name: 80-80 
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
