apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-sentiment-analysis-deployment
  labels:
    app: my-sentiment-analysis-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-sentiment-analysis-api
  template:
    metadata:
      labels:
        app: my-sentiment-analysis-api
    spec:
      containers:
      - name: my-sentiment-analysis-api
        image: datascientest/fake-api:1.0.0
        ports:
        - containerPort: 8000
        env:
        - name: ENVIRONMENT_TYPE
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: my-key