apiVersion: v1
kind: Service
metadata:
  name: my-exam-service
  labels:
    app: exam-api
spec:
  type: ClusterIP
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: exam-api